development:
  adapter: postgresql
  encoding: unicode
  database: skrimply_development
  pool: 5
  username: mario
  password:
  host: localhost

test: &test
  adapter: postgresql
  encoding: unicode
  database: skrimply_test
  pool: 5
  username: mario
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: skrimply_production
  pool: 5
  username: mario
  password:
  host: localhost

cucumber:
  <<: *test